## Applying Numpy to tables & Calculations


Suppose there are book sales happening in a week where 3 books are sold in different amounts. At the end of the week we want to calculate the total amount sold from each book and the total amount sold daily from all books.

In [1]:
import numpy as np

books_sold = np.random.randint(15, size=(5, 3))
books_sold

array([[ 8, 11, 13],
       [12,  5,  4],
       [14,  8,  0],
       [ 2,  7, 10],
       [ 7,  3,  7]])

In [2]:
import pandas as pd

sell_data = pd.DataFrame(books_sold,
                         index=['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                         columns=['Action', 'Romance', 'Educational']
                        )
sell_data

Action  Romance  Educational
Mon       8       11           13
Tue      12        5            4
Wed      14        8            0
Thu       2        7           10
Fri       7        3            7

Calculating total sold per day

In [3]:
prices = np.array([10, 12, 8])

In [8]:
prices.T.shape, books_sold.shape

((3,), (5, 3))

In [9]:
prices

array([10, 12,  8])

In [11]:
prices = prices.reshape((3, 1))
prices

array([[10],
       [12],
       [ 8]])

In [14]:
books_sold.shape, prices.shape

((5, 3), (3, 1))

In [15]:
daily_totals = np.dot(books_sold, prices)
daily_totals

array([[316],
       [212],
       [236],
       [184],
       [162]])

In [16]:
sell_data

Action  Romance  Educational
Mon       8       11           13
Tue      12        5            4
Wed      14        8            0
Thu       2        7           10
Fri       7        3            7

In [31]:
prices = prices.reshape((1, 3))

In [32]:
price_data = pd.DataFrame(prices,
                         index=['Prices'],
                         columns=['Action', 'Romance', 'Educational']
                        )
price_data

Action  Romance  Educational
Prices      10       12            8

In [33]:
sell_data['Total ($)'] = daily_totals
sell_data

Action  Romance  Educational  Total ($)
Mon       8       11           13        316
Tue      12        5            4        212
Wed      14        8            0        236
Thu       2        7           10        184
Fri       7        3            7        162