In [1]:
import numpy as np

# Numpy, DataTypes & Attributes

Main datatype is `ndarray` for n-dimensional array.

In [4]:
# 1D
a1 = np.array([1, 2, 3])
# 2D
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Rows, cols
a2.shape

(2, 3)

You can view number of dimensions through: `arr.ndim`

In [6]:
a1.ndim, a2.ndim

(1, 2)

In [7]:
# Number of elements
a2.size

6

In [8]:
type(a1)

numpy.ndarray

### Create df from ndarray

In [9]:
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## Creating np arrays

In [10]:
ones = np.ones((3, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
range_arr = np.arange(1, 10, 2)
range_arr

array([1, 3, 5, 7, 9])

In [12]:
rand_nd_arr = np.random.randint(1, 10, (4, 5))
rand_nd_arr

array([[9, 2, 3, 9, 4],
       [9, 2, 1, 9, 4],
       [5, 1, 5, 4, 8],
       [5, 8, 4, 5, 4]])

In [14]:
rand_nd_arr2 = np.random.random((3, 4))
rand_nd_arr2

array([[0.28033319, 0.69320493, 0.1410107 , 0.83950822],
       [0.05020783, 0.42485319, 0.69599998, 0.33508208],
       [0.35426995, 0.53348203, 0.25780237, 0.30059705]])

In [16]:
rand_nd_arr3 = np.random.rand(3, 4)
rand_nd_arr3

array([[0.36001088, 0.60196958, 0.41274975, 0.0225136 ],
       [0.26152616, 0.71011438, 0.94846637, 0.97160124],
       [0.12160709, 0.78707276, 0.00714423, 0.53652382]])